
為何使用 numpy 而不是 list？
https://www.perplexity.ai/search/0638400d-59de-4d83-8e38-0cb807daf590

In [1]:
import numpy as np
from numpy import ndarray

my_array:ndarray = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%time 

for _ in range(10):
    #list的comprehension,list綜合表達式
    my_lists = [x*2 for x in my_list]

CPU times: total: 0 ns
Wall time: 0 ns


In [3]:
%time for _ in range(10): my_array2 = my_array * 2

CPU times: total: 93.8 ms
Wall time: 97 ms


In [6]:

#tuple,1個元素的表示法
(4, 5)
type((4,))

tuple

In [7]:
np.array(range(4)).shape

(4,)


### 50個學生,每個學生有5個分數,每個分數50~100

In [4]:
np.random.seed(42)  # 設定亂數種子為42 ，固定 NumPy 產生的亂數，使每次執行程式時都能得到相同的亂數結果，可以使用 np.random.seed()
scores=np.random.randint(50,101,(50,5))
scores

array([[ 88,  78,  64,  92,  57],
       [ 70,  88,  68,  72,  60],
       [ 60,  73,  85,  89,  73],
       [ 52,  71,  51,  73,  93],
       [ 79,  87,  51,  70,  82],
       [ 61,  71,  93,  74,  98],
       [ 76,  91,  77,  65,  64],
       [ 96, 100,  93,  52,  86],
       [100,  56,  70,  58,  88],
       [ 67,  53,  74,  63,  99],
       [ 58,  75,  51,  69,  77],
       [ 96,  56,  93,  57,  96],
       [ 84,  63,  66,  85,  99],
       [ 89,  53,  51,  55,  91],
       [ 53,  78,  67,  75,  93],
       [ 83,  59,  85,  63,  80],
       [ 97,  64,  57,  63,  72],
       [ 89,  70,  65,  94,  67],
       [ 96,  73,  75,  74,  94],
       [ 90,  78,  64,  94,  50],
       [ 74,  56,  58,  73,  50],
       [ 93,  57,  73,  60, 100],
       [ 66,  57,  84,  84,  82],
       [ 54,  91,  88,  90,  77],
       [ 56,  58,  57,  61,  83],
       [ 82,  97,  72,  73,  86],
       [ 84,  93,  89,  71,  76],
       [ 84,  50,  84,  86,  96],
       [ 63,  52,  50,  54,  75],
       [ 63,  

In [5]:
#ndarray常用實體屬性
scores.ndim
scores.shape
scores.size
scores.dtype

dtype('int32')

### 基本索引和分割
- ndarray[index] 
- ndarray[start:end:step]

基本索引
一維陣列索引：類似 Python list，用方括號 [] 取得元素，例如 a[2] 取第三個元素。

多維陣列索引：使用逗號分隔各維度索引，如 a[1,[2] 取第2列第3行元素。

切片 (slicing)：使用 start:stop:step，例如 a[1:4] 取第2到第4個元素（不包含第5個），多維陣列可對各維度切片，如 a[1:3, 2:]。

省略號 ...：用於多維陣列中省略部分維度，如 a[..., 1] 表示取最後一維的第2個元素。

陣列分割
NumPy 提供多種分割函數，常用的有：

np.split(array, indices_or_sections, axis=0)：將陣列沿指定軸分割成多個子陣列，indices_or_sections 可是整數或分割位置列表，分割數需能整除陣列大小。

np.array_split(array, indices_or_sections, axis=0)：與 split 類似，但允許不均等分割。

np.hsplit(array, sections)：沿水平方向（axis=1）分割，等同 split 且 axis=1。

np.vsplit(array, sections)：沿垂直方向（axis=0）分割，等同 split 且 axis=0。

np.dsplit(array, sections)：沿深度方向（axis=2）分割，適用於3維以上陣列。

In [15]:
#2維
scores[0] #array([88, 78, 64, 92, 57], dtype=int32)
scores[0][4] #類似list的操作 np.int32(57)
scores[0, 4] #ndarrya的slice的操作法 --常用這個 np.int32(57)

np.int32(57)

In [ ]:
# 取得第一位學生的分數
scores[0] #shape(5,0) array([88, 78, 64, 92, 57], dtype=int32)
scores[0,:] #shape(5,0) array([88, 78, 64, 92, 57], dtype=int32)
scores[0:1,:] #shape(1,5) array([[88, 78, 64, 92, 57]], dtype=int32)


array([88, 78, 64, 92, 57], dtype=int32)

In [18]:
# 取得第1,2位學生的分數
scores[:2]
scores[:2,:]
scores[(0,1),:]

array([[88, 78, 64, 92, 57],
       [70, 88, 68, 72, 60]], dtype=int32)

In [19]:

## 取得第1,2,5位學生的分數
scores[(0,1,4),:]

array([[88, 78, 64, 92, 57],
       [70, 88, 68, 72, 60],
       [79, 87, 51, 70, 82]], dtype=int32)

In [21]:
## 取得第1科所有的分數
scores[:0] #(50,0)
scores[:,0:1] #(1,50)

array([[ 88],
       [ 70],
       [ 60],
       [ 52],
       [ 79],
       [ 61],
       [ 76],
       [ 96],
       [100],
       [ 67],
       [ 58],
       [ 96],
       [ 84],
       [ 89],
       [ 53],
       [ 83],
       [ 97],
       [ 89],
       [ 96],
       [ 90],
       [ 74],
       [ 93],
       [ 66],
       [ 54],
       [ 56],
       [ 82],
       [ 84],
       [ 84],
       [ 63],
       [ 63],
       [ 64],
       [ 81],
       [ 79],
       [ 64],
       [ 81],
       [ 51],
       [ 77],
       [ 60],
       [ 50],
       [ 88],
       [ 86],
       [ 73],
       [ 90],
       [ 51],
       [ 66],
       [ 72],
       [ 68],
       [ 55],
       [ 87],
       [ 71]], dtype=int32)

In [22]:
## 取得第1,2科所有的分數
scores[:,:2] #(50,2)

array([[ 88,  78],
       [ 70,  88],
       [ 60,  73],
       [ 52,  71],
       [ 79,  87],
       [ 61,  71],
       [ 76,  91],
       [ 96, 100],
       [100,  56],
       [ 67,  53],
       [ 58,  75],
       [ 96,  56],
       [ 84,  63],
       [ 89,  53],
       [ 53,  78],
       [ 83,  59],
       [ 97,  64],
       [ 89,  70],
       [ 96,  73],
       [ 90,  78],
       [ 74,  56],
       [ 93,  57],
       [ 66,  57],
       [ 54,  91],
       [ 56,  58],
       [ 82,  97],
       [ 84,  93],
       [ 84,  50],
       [ 63,  52],
       [ 63,  88],
       [ 64,  75],
       [ 81,  88],
       [ 79,  86],
       [ 64,  92],
       [ 81,  56],
       [ 51,  91],
       [ 77,  93],
       [ 60,  77],
       [ 50,  76],
       [ 88,  55],
       [ 86,  82],
       [ 73,  64],
       [ 90,  98],
       [ 51,  52],
       [ 66,  98],
       [ 72,  86],
       [ 68,  51],
       [ 55,  81],
       [ 87,  73],
       [ 71,  60]], dtype=int32)

In [ ]:
## 取得前30位同學的最後3科的分數
scores[:30,-3:] #(30,3)

array([[ 64,  92,  57],
       [ 68,  72,  60],
       [ 85,  89,  73],
       [ 51,  73,  93],
       [ 51,  70,  82],
       [ 93,  74,  98],
       [ 77,  65,  64],
       [ 93,  52,  86],
       [ 70,  58,  88],
       [ 74,  63,  99],
       [ 51,  69,  77],
       [ 93,  57,  96],
       [ 66,  85,  99],
       [ 51,  55,  91],
       [ 67,  75,  93],
       [ 85,  63,  80],
       [ 57,  63,  72],
       [ 65,  94,  67],
       [ 75,  74,  94],
       [ 64,  94,  50],
       [ 58,  73,  50],
       [ 73,  60, 100],
       [ 84,  84,  82],
       [ 88,  90,  77],
       [ 57,  61,  83],
       [ 72,  73,  86],
       [ 89,  71,  76],
       [ 84,  86,  96],
       [ 50,  54,  75],
       [ 76,  58,  64]], dtype=int32)

### ndarray 的統計的實體方法
- sum()
- min()
- max()
- mean()

In [ ]:
# 每個學生的總分數
scores.sum(axis=1) #ndarray 實體方法
 np.sum(scores,axis=1) #numpy的globle 的function

array([379, 358, 380, 340, 369, 397, 373, 427, 372, 356, 330, 398, 397,
       339, 366, 370, 353, 385, 412, 376, 311, 383, 373, 400, 315, 410,
       413, 400, 294, 349, 392, 401, 419, 381, 385, 368, 411, 381, 330,
       334, 452, 372, 435, 385, 343, 371, 368, 315, 352, 375])

In [ ]:
# 取得前30位學生的平均
scores[0:30].mean(axis=1) #ndarray 實體方法

np.mean(scores[:30],axis=1) #numpy的globle 的function

array([75.8, 71.6, 76. , 68. , 73.8, 79.4, 74.6, 85.4, 74.4, 71.2, 66. ,
       79.6, 79.4, 67.8, 73.2, 74. , 70.6, 77. , 82.4, 75.2, 62.2, 76.6,
       74.6, 80. , 63. , 82. , 82.6, 80. , 58.8, 69.8])

In [28]:
#第1科最高的分數和最低分數
scores[:,0].max(axis=0) # np.int32(100)
scores[:,0].min(axis=0) # np.int32(50)

np.int32(50)